# Warsaw parking dataset — workbench

Data: `silver/parking_dataset.csv` — one row per parking per snapshot, all columns flat.

To refresh: run `ping/ping_parkings.py` (new snapshot), then `transform/build_silver.py` (rebuild CSV), then re-run the cell below.

In [2]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PROJECT = Path.cwd().parent if Path.cwd().name == "eda" else Path.cwd()

df = pd.read_csv(PROJECT / "silver" / "parking_dataset.csv",
                 parse_dates=["source_ts", "ingested_at"])
# note: source_ts is naive Warsaw local time; ingested_at is UTC

print(df.shape)

(98, 59)

In [3]:
df.head()

,parking_id,name,source_ts,ingested_at,free_public,free_disabled,free_electric,total_standard,total_disabled,total_electric,...,price_motorcycle_2h,price_motorcycle_3h,price_motorcycle_4h,price_van_0h,price_van_1h,price_van_24h,price_van_2h,price_van_3h,price_van_4h,security
0,parking_na_pl._żelaznej_bramy,Parking na Pl. Żelaznej Bramy,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,12,0,0,47,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony
1,parking_pałac_kultury_i_nauki,Parking Pałac Kultury i Nauki,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,252,0,0,603,22,1,...,NaN,NaN,NaN,10.0,30.0,450.0,NaN,NaN,NaN,NaN
2,parking_pl._powstańców_warszawy,Parking Pl. Powstańców Warszawy,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,297,15,7,396,16,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,parking_pod_placem_krasińskich,PARKING POD PLACEM KRASIŃSKICH,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,96,0,0,356,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,parking_pod_ulicą_waryńskiego,PARKING POD ULICĄ WARYŃSKIEGO,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,21,0,0,130,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.sort_values(["total_standard", "source_ts"],ascending=False)          # orderBy first!

In [16]:
df.head()

,parking_id,name,source_ts,ingested_at,free_public,free_disabled,free_electric,total_standard,total_disabled,total_electric,...,price_motorcycle_2h,price_motorcycle_3h,price_motorcycle_4h,price_van_0h,price_van_1h,price_van_24h,price_van_2h,price_van_3h,price_van_4h,security
11,parking_przy_ul._karasia,Parking przy ul. Karasia,2026-07-10 12:21:05,2026-07-10 10:21:29.327023+00:00,4,0,0,24,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony
25,parking_przy_ul._karasia,Parking przy ul. Karasia,2026-07-10 12:22:05,2026-07-10 10:22:06.829438+00:00,4,0,0,24,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony
39,parking_przy_ul._karasia,Parking przy ul. Karasia,2026-07-10 12:23:05,2026-07-10 10:23:25.639315+00:00,4,0,0,24,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony
53,parking_przy_ul._karasia,Parking przy ul. Karasia,2026-07-10 14:56:04,2026-07-10 12:56:25.787688+00:00,4,0,0,24,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony
67,parking_przy_ul._karasia,Parking przy ul. Karasia,2026-07-10 15:13:05,2026-07-10 13:13:26.543065+00:00,4,0,0,24,0,0,...,11.0,14.0,18.0,NaN,6.0,102.0,13.0,18.0,22.0,Parking strzeżony